language: node_js
node_js:
    - 10
cache: npm
install:
    - npm install
script:
    - node ./cdn.js
    - npm run docs:build
after_success:
    - cd ./.vuepress/dist
    - git init
    - git config --global user.name "${U_NAME}"
    - git config --global user.email "${U_EMAIL}"
    - git add -A
    - git commit -m 'deploy'
    - git push --force "https://${GE_TOKEN}@${GE_REF}" master:${P_BRANCH}
    - git push --force "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
branches:
  only:
    - master
env:
    global:
        - GE_REF: gitee.com/clinan/clinan.github.io.git
        - GH_REF: github.com/clinan/clinan.github.io.git
        